version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - grace-worker-network

  web:
    image: grace-web:latest
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - grace-worker-network
    stop_grace_period: 30s

  worker1:
    image: grace-worker:latest
    container_name: worker1
    depends_on:
      - redis
    networks:
      - grace-worker-network
    stop_grace_period: 168h

  worker2:
    image: grace-worker:latest
    container_name: worker2
    depends_on:
      - redis
    networks:
      - grace-worker-network
    stop_grace_period: 168h
